name: .NET Build/Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ./src/PledgeManager.Web/PledgeManager.Web.csproj
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish Web
        run: dotnet publish src/PledgeManager.Web -c Release -o out
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: out
